_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 1
                - 5
            "12": 0.18.6
            "13": linux-x86_64
architecture:
    value: ESM + FNN
batch_szie:
    value: 16
dataset:
    value: corpus_200_500_Viruses_random, corpus_200_500_Non_Viruses_random
epochs:
    value: 100000
learning_rate:
    value: 0.001
max_seq_len:
    value: 500
