_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.14
            "5": 0.18.7
            "6": 4.46.2
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
        visualize:
            val/confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: val/confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
architecture:
    value: Freeze ESM
batch_szie:
    value: 16
dataset:
    value: corpus_200_500_Viruses_random, corpus_200_500_Non_Viruses_random
epochs:
    value: 100000
learning_rate:
    value: 0.001
max_seq_len:
    value: 500
